column:
  - id: int
  - Gender: category
  - Age: int
  - Driving_Licence: int
  - Region_Code: int
  - Previously_Insured: int
  - Vehicle_Age: category
  - Vehicle_Damage: category
  - Annual_Premium: float
  - Policy_Sales_Channel: float
  - Vintage: int
  - Response: int

numerical_columns:
  - Age
  - Region_Code
  - Previously_Insured
  - Annual_Premium
  - Policy_Sales_Channel
  - Vintage
  - Response

categorical_columns:
  - Gender
  - Vehicle_Age
  - Vehicle_Damage
drop_columns: _id

#for datatransformation
num_features:
  - Age
  - Vintage

mm_colums:
  - Annual_Premium
    
